References
----------
.. [CIT1] \A. Dubey, A. Bose, M. Liu and L. N. Ochoa, "Paving the Way for Advanced Distribution Management Systems Applications: Making the Most of Models and Data," in *IEEE Power and Energy Magazine*, vol. 18, no. 1, pp. 63-75, Jan.-Feb. 2020
.. [CIT2] \Rahul R Jha; Anamika Dubey and Kevin P. Schneider, "Coordinated Control for Voltage Regulation of Unbalanced Power Distribution System: Centralized and Local Control Methods," in *IET Smart Grid (Submitted)*.
.. [CIT3] \Rahul R. Jha; Anamika Dubey; Chen-Ching Liu; Kevin P. Schneider, “Bi-level Volt-VAR Optimization to Coordinate Smart Inverters with Voltage Control Devices”, in *IEEE Transaction on Power System*,  vol.  34,  no.  3,  pp.  1801–1813,2019.
.. [CIT4] \R. R. Jha and A. Dubey, “Exact distribution optimal power flow (d-opf)model  using  convex  iteration  technique,”  *2019  IEEE  Power  EnergySociety General Meeting (PESGM)*, Aug 2019, pp. 1–5.
.. [CIT5] \Rahul R Jha and  Anamika Dubey,“Coordinated Voltage Control for Conservation Voltage Reduction in Power Distribution Systems”,  *IEEE Power and Energy Society General Meeting (PESGM)*, Aug 2020, pp. 1–5.
.. [CIT6] \Rahul R. Jha, S. Poudel, A. Dubey, and K. P. Schneider, “Volt-VAR Optimization Application Using GridAPPS-D -- Standards-Based Open-Source ADMS Platform,” *in prep for IEEE Power and Energy Technology Systems Journal*
.. [CIT7] \Rahul R Jha and Anamika Dubey,“Local Smart Inverter Control to Mitigate the Effects of Photovoltaic (PV) Generation Variability”,  in North American Power Symposium (NAPS) 2019.
.. [CIT9] \W. H. Kersting, "Radial distribution test feeders," in *2001 IEEE Power Engineering Society Winter Meeting. Conference Proceedings (Cat. No.01CH37194)*, 2001, pp. 908-912 vol.2.
.. [CIT10] \R. F. Arritt and R. C. Dugan, "The IEEE 8500-node test feeder," in *IEEE PES T&D 2010*, pp. 1-6.

	
